[package]
name = "tail_regex"
version = "0.1.0"
authors = ["Christo Stephenson <code@christo.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
termcolor = "1.1"
atty = "0.2"
dirs = "3.0"
